# Environment that uses CPU versions of all codes
name: fastforce
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10.*
  - pandas==1.*
  - pydantic
  - pymongo
  - tqdm
  - jupyterlab
  - matplotlib
  - tensorboard
  - pyg
  - pytest
  - pip
  - pip:
      - git+https://gitlab.com/WardLT/ase.git@twostep_nwc
      - colmena>=0.3.0
      - globus-cli
