dataset_factory:
  #  The root folder name for saving and loading the pre-processd and raw datasets.
  # If null, will be named after the factory used and packing strategy. (type: Union[str, null], default: data)
  root: null
  #A tuple describing the ratios to divide the full dataset into training, validation, and test
  #  datasets (default: (0.8, 0.1, 0.1)).(type: Union[Tuple[float, ], null], default: null)
  splits: [0.9,0.1,0.0]
#  The data loader batchsize (type: int, default: 1)
  batch_size: 8
  # Use packing to minimise padding values  (type: bool, default: False)
  use_packing: true
  #  Number of neighbors to use for building the k-nearest neighbors graph when using packing
  # ( type: int, default: 8)
  k: 28
  #  Cutoff distance of interatomc interactions in Angstroms. (type: float, default: 30.0)
  cutoff: 6.0
  #  The maximum number of atoms used by the PadMolecule transform if padding is used
  #  (type: int, default: 32)
  max_num_atoms: 87
  #  This transform rescales the QM9 dataset molecular total energy to an energy per-atom
  #  that does not include the single-atom energies. (type: bool, default: True)
  use_qm9_energy: false
  # Use for QM9 if calculations are to be done on a per atom basis
  use_standardized_energy: false
  #  Instance of poptorch.Options. (type: Union[Options, null], default: null)
  options: null

bench:
  # Use synthetic data on the device to disable host I/O. (type: bool, default: False)
  synthetic_data: false
  # The number of data parallel replicas. A negative value will run with CPU as device (type: int, default: 16)
  replication_factor: 8
  # The number of device iterations to use. (type: int, default: 6)
  device_iterations: 16
  # The number of mini-batches to accumulate for the gradient calculation. (type: int, default: 2)
  gradient_accumulation: 1
  # The learning rate used by the optimiser. (type: float, default: 0.001)
  learning_rate: 0.0007
  # The number of epochs to benchmark. (type: int, default: 10)
  num_epochs: 400
  # Run a single training step with profiling enabled and saves the profiling report to the provided location.
  #(type: Union[str, null], default: null)
  profile_dir: null
  # String used to indicate whether to run the water or QM9 dataset.
  # The default is QM9. Options are QM9 or water. (type: Union[str, null], default: qm9)
  factory: water
   # String used to indicate the water dataset to use. Options are 'train', 'test', 'all'.
  # The default value is train. The 500k water cluster dataset will be used
  # If the value is set to 'test'', the test data set will be used
  # If the vlalue is set to 'all', the entire 5 million water cluster data set will be used
  #  (type: Union[str, null], default: train)
  water_dataset: train
  # Use Weights and Biases to log benchmark results. (type: bool, default: False)
  use_wandb: true
  # If set to true, partial results for matrix multiplication and convolution operators
  half_precision: false
  # Number of workers used by the dataloader
  num_workers: 4
#  If true, will run dataloader construction time for each epoch(type: bool, default: False)
time_dataloader: false
# If using wandb, this will be the project in which results are stored  (type: str, default: schnet_bench)
project: test_train
# If using wandb, setting run_name will assign a user-given name to the run (type: Union[str, null], default: null)
run_name: schnet_bench
# If true, this will run validation in addition to training.
# If false, only training will be run  (type: bool, default: False)
validation: true
